[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session

# Регистрация маркеров
;markers =
;    unit: Unit tests (fast, no external dependencies)
;    integration: Integration tests (require database)
;    slow: Slow running tests

# Опции для лучшего вывода
addopts =
    --strict-markers
    --tb=short
    --disable-warnings